# Generated by Django 3.1.5 on 2021-08-02 09:54

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='termandcondition',
            name='company',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=api.models.today, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.companysetting'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='termandcondition',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=api.models.today, null=True),
        ),
        migrations.AddField(
            model_name='termandcondition',
            name='setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.companysetting'),
        ),
        migrations.AddField(
            model_name='termandcondition',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
