# Generated by Django 3.2.6 on 2021-08-21 15:02

from django.db import migrations, models
import django.db.models.deletion
import invoicegen_backend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=invoicegen_backend.utils.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
