# Generated by Django 3.2.6 on 2021-09-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0003_auto_20210906_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('dp', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dob', models.DateField(blank=True, default='', null=True)),
                ('dlNo', models.CharField(blank=True, default='', max_length=128, null=True, unique=True)),
                ('remark', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('createdBy', models.EmailField(blank=True, max_length=254)),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedBy', models.EmailField(blank=True, max_length=254)),
                ('modifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.driver')),
            ],
        ),
    ]
