# Generated by Django 3.2.6 on 2021-09-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_vehicle_vehicleregistrationno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehiclemodel',
            new_name='vehicleModel',
        ),
    ]
