# Generated by Django 3.2.6 on 2021-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_driver_driveraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='usearea',
            field=models.CharField(blank=True, default='SALE', max_length=50, null=True),
        ),
    ]
