# Generated by Django 3.2.6 on 2021-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_vehiclemodel_vehicle_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
