# Generated by Django 3.1.5 on 2021-08-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_driver_driveraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
