# Generated by Django 3.2.6 on 2021-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_vendor_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
