# Generated by Django 3.1.5 on 2021-08-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210815_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dp',
            field=models.URLField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
