# Generated by Django 3.1.5 on 2021-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_driver_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='createdBy',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='driver',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='modifiedBy',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='driver',
            name='modifiedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
