# Generated by Django 3.1.5 on 2021-08-02 09:16

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('uom', models.CharField(default='MT', max_length=20)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.plant')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('uom', models.TextField(default='MT')),
                ('qty', models.IntegerField()),
                ('date', models.DateField(blank=True)),
                ('vendor', models.TextField()),
                ('ponumber', models.TextField()),
                ('createdOn', models.DateTimeField(blank=True, default=api.models.today, null=True)),
                ('createdBy', models.EmailField(blank=True, max_length=254)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('modifiedBy', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(max_length=200)),
                ('materialCode', models.CharField(max_length=128)),
                ('materialUom', models.CharField(max_length=20)),
                ('materialQty', models.FloatField()),
                ('challanNo', models.CharField(max_length=128)),
                ('challanDate', models.CharField(max_length=128)),
                ('purchaseOrder', models.CharField(max_length=128)),
                ('vehicleNo', models.CharField(max_length=50)),
                ('driverName', models.CharField(max_length=200)),
                ('driverCode', models.CharField(max_length=128)),
                ('moisture', models.FloatField()),
                ('remark', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('createdOn', models.DateTimeField(blank=True, default=api.models.today, null=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('current', models.IntegerField()),
                ('createdOn', models.DateTimeField(blank=True, default=api.models.today, null=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.rawmaterial')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.plant')),
            ],
        ),
    ]
