# Generated by Django 3.2.6 on 2021-09-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current',
            field=models.FloatField(),
        ),
    ]
