# Generated by Django 3.2.6 on 2021-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawMaterialEntry',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='plant',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='createdBy',
            field=models.CharField(default='', max_length=50),
        ),
    ]
