# Generated by Django 3.2.6 on 2021-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210905_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='createdBy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
