# Generated by Django 3.2.6 on 2021-09-06 12:28

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poNumber', models.CharField(max_length=50)),
                ('orgName', models.CharField(blank=True, max_length=100)),
                ('orgAddrsLine1', models.TextField(blank=True, max_length=200)),
                ('orgAddrsLine2', models.TextField(blank=True, max_length=200)),
                ('orgAddrsLine3', models.TextField(blank=True, max_length=200)),
                ('orgEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('orgPhone', models.CharField(blank=True, max_length=13)),
                ('orgFax', models.CharField(blank=True, max_length=20)),
                ('orgState', models.CharField(blank=True, max_length=50)),
                ('orgCity', models.CharField(blank=True, max_length=50)),
                ('orgPostalCode', models.CharField(blank=True, max_length=8)),
                ('orgGSTIN', models.CharField(blank=True, max_length=15)),
                ('orgLogo', models.URLField(blank=True, null=True)),
                ('orgPanNo', models.CharField(default='', max_length=10)),
                ('vendorName', models.CharField(blank=True, max_length=50)),
                ('vendorAddrsLine1', models.CharField(blank=True, max_length=50)),
                ('vendorAddrsLine2', models.CharField(blank=True, max_length=50)),
                ('vendorAddrsLine3', models.CharField(blank=True, max_length=50)),
                ('vendorState', models.CharField(blank=True, max_length=50)),
                ('vendorCity', models.CharField(blank=True, max_length=50)),
                ('vendorPostalCode', models.CharField(blank=True, max_length=8)),
                ('vendorPhone', models.CharField(blank=True, max_length=50)),
                ('vendorEmail', models.CharField(blank=True, max_length=50)),
                ('vendorPanNo', models.CharField(blank=True, max_length=50)),
                ('vendorGSTIN', models.CharField(blank=True, max_length=50)),
                ('createdOn', models.DateTimeField(blank=True, default=api.models.today, null=True)),
                ('createdBy', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('uom', models.CharField(default='', max_length=50)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder')),
            ],
        ),
    ]
