# Generated by Django 3.2.6 on 2021-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='qty',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
