# Generated by Django 3.2.6 on 2021-09-06 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaseorderproduct_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxName', models.CharField(default='', max_length=100)),
                ('taxPercent', models.FloatField()),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder')),
            ],
        ),
    ]
