# Generated by Django 3.2.6 on 2021-09-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseordertax'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='costcenter',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
