# Generated by Django 3.2.6 on 2021-09-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20210907_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='po',
        ),
        migrations.RemoveField(
            model_name='purchaseordertax',
            name='po',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderProduct',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderTax',
        ),
    ]
