# Generated by Django 3.2.6 on 2021-09-07 08:10

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0006_auto_20210907_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poNumber', models.CharField(max_length=100, unique=True)),
                ('orgName', models.CharField(blank=True, max_length=100)),
                ('orgAddrsLine1', models.TextField(blank=True, max_length=200)),
                ('orgAddrsLine2', models.TextField(blank=True, max_length=200)),
                ('orgAddrsLine3', models.TextField(blank=True, max_length=200)),
                ('orgEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('orgPhone', models.CharField(blank=True, max_length=13)),
                ('orgFax', models.CharField(blank=True, max_length=20)),
                ('orgState', models.CharField(blank=True, max_length=50)),
                ('orgCity', models.CharField(blank=True, max_length=50)),
                ('orgPostalCode', models.CharField(blank=True, max_length=8)),
                ('orgGSTIN', models.CharField(blank=True, max_length=15)),
                ('orgLogo', models.URLField(blank=True, null=True)),
                ('orgPanNo', models.CharField(default='', max_length=10)),
                ('vendorName', models.CharField(blank=True, max_length=50)),
                ('vendorAddrsLine1', models.CharField(blank=True, max_length=50)),
                ('vendorAddrsLine2', models.CharField(blank=True, max_length=50)),
                ('vendorAddrsLine3', models.CharField(blank=True, max_length=50)),
                ('vendorState', models.CharField(blank=True, max_length=50)),
                ('vendorCity', models.CharField(blank=True, max_length=50)),
                ('vendorPostalCode', models.CharField(blank=True, max_length=8)),
                ('vendorPhone', models.CharField(blank=True, max_length=50)),
                ('vendorEmail', models.CharField(blank=True, max_length=50)),
                ('vendorPanNo', models.CharField(blank=True, max_length=50)),
                ('vendorGSTIN', models.CharField(blank=True, max_length=50)),
                ('shipToName', models.CharField(blank=True, max_length=50)),
                ('shipToAddrsLine1', models.CharField(blank=True, max_length=50)),
                ('shipToAddrsLine2', models.CharField(blank=True, max_length=50)),
                ('shipToAddrsLine3', models.CharField(blank=True, max_length=50)),
                ('shipToState', models.CharField(blank=True, max_length=50)),
                ('shipToCity', models.CharField(blank=True, max_length=50)),
                ('shipToPostalCode', models.CharField(blank=True, max_length=8)),
                ('shipToPhone', models.CharField(blank=True, max_length=50)),
                ('shipToEmail', models.CharField(blank=True, max_length=50)),
                ('shipToPanNo', models.CharField(blank=True, max_length=50)),
                ('shipToGSTIN', models.CharField(blank=True, max_length=50)),
                ('poTotalAmount', models.FloatField()),
                ('poTotalAmountWithTax', models.FloatField()),
                ('costcenter', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('createdOn', models.DateTimeField(blank=True, default=api.models.today, null=True)),
                ('createdBy', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxName', models.CharField(default='', max_length=100)),
                ('taxPercent', models.FloatField()),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('uom', models.CharField(default='', max_length=50)),
                ('qty', models.FloatField()),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder')),
            ],
        ),
    ]
