# Generated by Django 3.2.6 on 2021-09-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_purchaseorder_purchaseorderproduct_purchaseordertax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='costcenter',
            new_name='costCenter',
        ),
    ]
