# Generated by Django 3.2.6 on 2021-09-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_rename_costcenter_purchaseorder_costcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
