# Generated by Django 3.2.6 on 2021-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20210907_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='createdBy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
