# Generated by Django 3.2.6 on 2021-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_alter_purchaseorder_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='deliveredQty',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
