# Generated by Django 3.2.6 on 2021-09-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_purchaseorderproduct_deliveredqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
