# Generated by Django 3.2.6 on 2021-09-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_purchaseorderproduct_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
