# Generated by Django 3.2.6 on 2021-09-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_purchaseorder_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
