# Generated by Django 3.2.6 on 2021-09-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_auto_20210908_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='deliveredQty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
