from django.contrib import admin
from account.models import *

admin.site.register(Company)
admin.site.register(CompanyAddress)
admin.site.register(Plant)
admin.site.register(Address)
admin.site.register(Customer)
admin.site.register(Ids)
admin.site.register(IdsMap)
admin.site.register(Employee)
admin.site.register(Driver)
admin.site.register(EmployeeAddress)
admin.site.register(EmployeeType)
admin.site.register(Vehicle)
admin.site.register(Vendor)
admin.site.register(VendorAddress)
admin.site.register(Tax)
admin.site.register(UserNote)
admin.site.register(EmailTemplate)
admin.site.register(TermAndCondition)
admin.site.register(CompanySetting)