# Generated by Django 3.2.6 on 2021-09-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='siteDistance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
